export const VisibleTabs = {
  SHOW_HOME: "SHOW_HOME",
  SHOW_LAIR: "SHOW_LAIR",
  SHOW_HUNT: "SHOW_HUNT",
  SHOW_CONQUEST: "SHOW_CONQUEST",
  SHOW_SETTINGS: "SHOW_SETTINGS",
};

export const OffspringButtons = {
  OFFSPRING_KILL: "OFFSPRING_KILL",
  OFFSPRING_PROMOTE: "OFFSPRING_PROMOTE",
  OFFSPRING_WAR: "OFFSPRING_WAR",
  OFFSPRING_HUNT: "OFFSPRING_HUNT",
};

export const maleNames = [
  "Meivrum",
  "The Protective Froldrom",
  "Protector Of The Sky Pondud",
  "The Powerful One Kymru",
  "The Hungry Egiass",
  "Destroyer Of Men Chyrsid",
  "Champion Of The Yellow Runeit",
  "Lord Of Fire Bayghedat",
  "Champion Of The Skies Yrveru",
  "Lord Of The White Xelzrudei",
  "The WarmMeivrum",
  "The Protective Froldrom",
  "Protector Of The Sky Pondud",
  "The Powerful One Kymru",
  "The Hungry Egiass",
  "Destroyer Of Men Chyrsid",
  "Champion Of The Yellow Runeit",
  "Lord Of Fire Bayghedat",
  "Champion Of The Skies Yrveru",
  "Lord Of The White Xelzrudei",
  "The Warm",
  "Grymre",
  "The Protective Jymbiss",
  "Eater Of Bunnies Breghad",
  "The Insane Emmu",
  "Destroyer Of Men Biargum",
  "The Brave Bryzzyn",
  "Lord Of The Blue Friersiass",
  "Firebreath Gielberaym",
  "The Clumsy One Tinnero",
  "Protector Of Life Redrynad",
  "Lord Of Fire",
  "Noirgo",
  "The Tall Nirsed",
  "Lord Of The Skies Unneiss",
  "The Tyrant Dolbom",
  "Lord Of Fire Frorsass",
  "Destroyer Of Men Ximmid",
  "Lord Of The White Kiersonth",
  "The Warm Grondintum",
  "The Slow Jurdedess",
  "The Adorable Pairdysdyn",
  "Champion Of The Red",
  "Nyrre",
  "Protector Of Creatures Taisi",
  "Lord Of Fire Oddrig",
  "The Eternal One Kume",
  "The Evil One Geotais",
  "Champion Of The Skies Beimbym",
  "The Quiet Ruvad",
  "Lord Of The Brown Zataness",
  "Lord Of The Brown Nyrvinti",
  "The Gifted Izayntuss",
  "The Hungry",
  "Coldrur",
  "Champion Of Men Edias",
  "The Mammoth Eghorth",
  "Lord Of The Blue Kani",
  "The Clumsy One Marsum",
  "The Stubborn Xado",
  "The Dark Immun",
  "Lord Of The Brown Chatisdeg",
  "The Life Giver Grirviecro",
  "Lord Of The Yellow Nyndacru",
  "The Grumpy",
  "Brummuss",
  "Champion Of Men Iky",
  "Protector Of The Forest Brerin",
  "Bringer Of Death Jyddrut",
  "Firebreath Chembi",
  "Eater Of Sheep Britenth",
  "The Bright Ydois",
  "Champion Of The Skies Tembare",
  "The Fast One Xialricren",
  "The Voiceless Chelryronth",
  "Gentleheart",
];

export const femaleNames = [
  "Anath",
  "The Scary Rykil",
  "The Nocturnal Pekieth",
  "The Adorable Noka",
  "The Gifted One Orrilth",
  "The Deathlady Raindrunth",
  "Lady Of The Blue Dari",
  "The Swift Lozuna",
  "The Tender Aldridilth",
  "The Fierce Frergino",
  "The Puny",
  "Sonne",
  "Warmheart Sharmi",
  "The Eternal One Ripha",
  "Champion Of The Blue Chape",
  "The Gentle Garsyt",
  "Champion Of The Red Melli",
  "The Fast One Gemryr",
  "The Taker Of Life Shundieruth",
  "Lady Of The Brown Hynnedat",
  "The Strong Servody",
  "The Mysterious",
  "Tarlys",
  "Eater Of Sheep Agierth",
  "The Adorable Syrgun",
  "The Squeeler Faymu",
  "Champion Of Men Daekiet",
  "Champion Of The Yellow Dyvoss",
  "Eater Of Sheep Zonel",
  "Champion Of The Green Tatholo",
  "Champion Of The Green Tuthude",
  "The Voiceless One Vamraphyth",
  "The Voiceless One",
  "Gurlith",
  "The Magnificent Bophinth",
  "Protector Of The Sky Chisse",
  "Destroyer Of Life Sharvyth",
  "The Dead Cevno",
  "Lady Of The Blue Evurth",
  "The Clumsy One Bosath",
  "The Rabbit Slayer Tirvophylth",
  "The Puny Vapilirth",
  "The Quiet Myzissos",
  "The Jealous One",
  "Ukyt",
  "Champion Of Dragons Hoghin",
  "The Voiceless Cydheoss",
  "The Dark Pairla",
  "The Creep Endi",
  "The Fierce Urrot",
  "Gentle Mind Shukot",
  "The Jealous One Yssyphal",
  "The Gifted Esarroa",
  "The Tiran Gidorrys",
  "The Powerful One",
  "Qirgot",
  "The Voiceless One Fravy",
  "The Mysterious One Iormur",
  "The Evil One Hoadar",
  "Lady Of The Black Emoss",
  "The Tiran Zirlio",
  "The Loud Froross",
  "The Bright Gersedal",
  "The Tender Rymrenyth",
  "The Gentle Hadhayphan",
  "The Fast One",
  "Qipaer",
  "The Skinny One Havni",
  "Protector Of The Sky Yvnyss",
  "The Powerful Vimrinth",
  "The Life Giver Firlilth",
  "The Mysterious One Sipilth",
  "The Grumpy Venny",
  "Lady Of Fire Frezida",
  "The Tiran Haitide",
  "The Strong Cathadin",
  "The Mysterious One",
];
