export const VisibleTabs = {
  SHOW_HOME: "SHOW_HOME",
  SHOW_LAIR: "SHOW_LAIR",
  SHOW_HUNT: "SHOW_HUNT",
  SHOW_CONQUEST: "SHOW_CONQUEST",
  SHOW_SETTINGS: "SHOW_SETTINGS",
};

export const OffspringButtons = {
  OFFSPRING_KILL: "OFFSPRING_KILL",
  OFFSPRING_PROMOTE: "OFFSPRING_PROMOTE",
  OFFSPRING_WAR: "OFFSPRING_WAR",
  OFFSPRING_HUNT: "OFFSPRING_HUNT",
};
